[tool.poetry]
name = "langchaintest"
version = "0.1.0"
description = ""
authors = ["Kai Breitbarth <kai.breitbarth@amanngirrbach.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
langchain = "^0.0.200"
#openai = "^0.27.8"
poetry-dotenv-plugin = "^0.1.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
